# Site settings
title: Linda Roesch
description: "Informatics Fellowship - Description"  # used in site head

# register on google analytics and replace this token
google_analytics: UA-75681059-1

# footer details. Deleting the value would remove it from footer.
github_username:  
linklinkedin_username:  
email: 
rss : true

# used for portfolio on home page
collections:
  - portfolio

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate. for paginating blog posts.
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
